name: Server
on:
  push:
    branches:
      - github-ci
    paths:
      - 'server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'server/**'
defaults:
  run:
    working-directory: server
jobs:
  test-server:
    name: Test IdeaLS server
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: server
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report-${{ matrix.os }}
          path: "build/reports/tests/test/**/*.*"
  build-idea-plugin:
    name: Build IdeaLS plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build plugins
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :buildPlugin
          build-root-directory: server
      - uses: actions/upload-artifact@v3
        with:
          name: IdeaLS plugin
          path: "build/distributions/*.zip"
