name: Server
on:
  push:
    branches:
      - actions-ci
defaults:
  run:
    working-directory: server
jobs:
  test-server:
    name: Test IdeaLS server
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: server
  build-idea-plugin:
    name: Build IdeaLS plugin
    needs:
      - test-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build plugins
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :buildPlugin
          build-root-directory: server
      - uses: actions/upload-artifact@v3
        with:
          name: IdeaLS plugin
          path: "server/build/distributions/*.zip"
